version: "3"
services:
  web:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8080 portfolio.wsgi"
    ports:
      - "8000:8080"
    depends_on:
      - nginx
  nginx:
    image: "nginx"
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    ports:
      - "80:80"
