version: "3"
services:
  web:
    build: .
    restart: on-failure
    volumes:
      - /var/log/gunicorn:/var/log/gunicorn
      - .:/www
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8080 portfolio.wsgi:application --access-logfile '/var/log/gunicorn/access.log' --error-logfile '/var/log/gunicorn/error.log'"
    ports:
      - "8000:8080"
  nginx:
    image: "nginx"
    restart: always
    volumes:
#      - /var/log/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    ports:
      - "80:80"
    depends_on:
      - web
