# Generated by Django 2.1.7 on 2019-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=45)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('message', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('path', models.ImageField(upload_to='photos')),
                ('page', models.CharField(max_length=150)),
            ],
        ),
    ]
